# 11.5. 축퇴 준위의 섭동론

In [1]:
import numpy as np

eps = 0.02
states = [(1, 1, 2), (1, 2, 1), (2, 1, 1)]

W = np.diag([-eps * (2 * ny**2 + 4 * nz**2) for (nx, ny, nz) in states])

print("섭동 행렬 W (E_0 단위):")
print(np.round(W, 4))

E1, C = np.linalg.eigh(W)
print(f"\n1차 보정: {np.round(E1, 4)}")
print(f"보정 에너지: {np.round(6 + E1, 4)}")


def exact(a, b, c, state):
    nx, ny, nz = state
    return (nx / a) ** 2 + (ny / b) ** 2 + (nz / c) ** 2


a, b, c = 1, 1 + eps, 1 + 2 * eps
print(f"\n{'상태':>8} {'1차 보정':>9} {'정확한 값':>8}")
for s in states:
    approx = 6 - eps * (2 * s[1] ** 2 + 4 * s[2] ** 2)
    print(f"{str(s):>10} {approx:10.4f} {exact(a, b, c, s):11.4f}")

섭동 행렬 W (E_0 단위):
[[-0.36  0.    0.  ]
 [ 0.   -0.24  0.  ]
 [ 0.    0.   -0.12]]

1차 보정: [-0.36 -0.24 -0.12]
보정 에너지: [5.64 5.76 5.88]

      상태     1차 보정    정확한 값
 (1, 1, 2)     5.6400      5.6594
 (1, 2, 1)     5.7600      5.7692
 (2, 1, 1)     5.8800      5.8857


In [2]:
import sympy as sp

r, theta, phi = sp.symbols("r theta phi", positive=True)

psi_2s = 1 / (4 * sp.sqrt(2 * sp.pi)) * (2 - r) * sp.exp(-r / 2)
psi_2pz = 1 / (4 * sp.sqrt(2 * sp.pi)) * r * sp.cos(theta) * sp.exp(-r / 2)
z = r * sp.cos(theta)


def braket(f, op, g):
    integrand = f * op * g * r**2 * sp.sin(theta)
    return sp.integrate(sp.integrate(sp.integrate(integrand, (phi, 0, 2 * sp.pi)), (theta, 0, sp.pi)), (r, 0, sp.oo))

print("<2s|z|2s>   =", sp.simplify(braket(psi_2s, z, psi_2s)))
print("<2pz|z|2pz> =", sp.simplify(braket(psi_2pz, z, psi_2pz)))
print("<2s|z|2pz>  =", sp.simplify(braket(psi_2s, z, psi_2pz)))

<2s|z|2s>   = 0
<2pz|z|2pz> = 0
<2s|z|2pz>  = -3


In [3]:
eF = 0.01

W = eF * np.array([[0, -3, 0, 0], [-3, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], dtype=float)

E1, C = np.linalg.eigh(W)

print("1차 보정:", np.round(E1, 5))
print("고유벡터 (열 방향):")
print(np.round(C, 4))

1차 보정: [-0.03  0.    0.    0.03]
고유벡터 (열 방향):
[[-0.7071  0.      0.     -0.7071]
 [-0.7071  0.      0.      0.7071]
 [-0.      1.      0.      0.    ]
 [-0.      0.      1.      0.    ]]
