# 11.2. 선형 변분 함수

In [1]:
import numpy as np
from scipy.constants import hbar, m_e, e, h
from scipy.linalg import eigh

L = 1e-9
x = np.linspace(0, L, 100001)
E_exact = h**2 / (8 * m_e * L**2) / e


def basis(n):
    basis_function = []
    for k in range(1, n + 1):
        f = (x * (L - x)) ** k
        basis_function.append(f / np.sqrt(np.trapezoid(f**2, x)))
    return basis_function


def matrices(B):
    S = np.array([[np.trapezoid(a * b, x) for b in B] for a in B])
    H = np.array([[hbar**2 / (2 * m_e) * np.trapezoid(np.gradient(a, x) * np.gradient(b, x), x) for b in B] for a in B])
    return H, S


B = basis(3)
H, S = matrices(B)
E, C = eigh(H, S)

print(f"참값 (n = 1): {E_exact:.10f} eV")
print(f"계산 결과    : {E[0] / e:.10f} eV")
print(f"오차        : {(E[0] / e - E_exact) / E_exact * 100:+.8f} % ")

참값 (n = 1): 0.3760301621 eV
계산 결과    : 0.3760301633 eV
오차        : +0.00000031 % 


In [2]:
print(f"{'Basis':>4} {'Energy (eV)':>14} {'Error':>14}")

for n in range(1, 5):
    H, S = matrices(basis(n))
    E, C = eigh(H, S)
    err = (E[0] / e - E_exact) / E_exact * 100
    print(f"{n:5d} {E[0] / e:14.8f} {err:+12.6f} %")

Basis    Energy (eV)          Error
    1     0.38099821    +1.321184 %
    2     0.37603569    +0.001471 %
    3     0.37603016    +0.000000 %
    4     0.37603016    -0.000000 %


In [3]:
H, S = matrices(basis(3))

s, U = np.linalg.eigh(S)
X = U @ np.diag(s**-0.5) @ U.T

print("X^T S X =")
print(np.round(X.T @ S @ X, 10))

H_prime = X.T @ H @ X
E_prime, C_prime = np.linalg.eigh(H_prime)

print(f"직교화 후 에너지: {E_prime[0] / e:.8f} eV")

X^T S X =
[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]
직교화 후 에너지: 0.37603016 eV
